[package]
name = "issue_me"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
crossterm = "0.27"
keyring = "2.3"
octocrab = "0.38"
ratatui = "0.26"
thiserror = "1.0"
tokio = { version = "1.38", features = ["macros", "rt-multi-thread"] }
